version: "3"

services:
  
  node:
    image: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/home/node/app
    ports:
      - 5000:5000
    command: "npm run dev"